name = "HydroPowerModels"
uuid = "baadc3fc-4b32-11e9-110e-59741390feb0"
authors = ["andrewrosemberg <andrew@ele.puc-rio.br>"]
version = "0.2.3"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SDDP = "f4570300-c277-11e8-125c-4912f86ce65d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DataFrames = "1"
CSV = "0.10"
JSON = "0.21"
JuMP = "1.6"
PowerModels = "0.19"
Reexport = "1"
SDDP = "1.1"
julia = "~1"

[extras]
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GLPK"]
